export enum Ville {
    ubersreik = 'Ubersreik',
    altdorf = 'Altdorf',
    frederheim = 'Frederheim',
    kutenholz = 'Kutenholz',
    coeurDeLaForet = 'Coeur de la forêt',
    brockel = 'Bröckel',
    mittelweg = 'Mittelweg',
    delberz = 'Delberz',
    sotturn = 'Sotturn',
    malstedt = 'Malstedt',
    grubentreich = 'Grubentreich',
    schoninghagen = 'Schoninghagen',
    dunkelbild = 'Dunkelbild',
    waldenhof = 'Waldenhof',
    heisenberg = 'Heisenberg',
    halstedt = 'Halstedt',
    middenheim = 'Middenheim',
}
